openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/auth/me/:
    get:
      operationId: listMes
      description: Return the authenticated user's profile.
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/titles/random/:
    get:
      operationId: randomTitle
      description: Return a random title bundle, optionally filtered by category.
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Title'
          description: ''
      tags:
      - api
  /api/titles/{id}/:
    get:
      operationId: retrieveTitle
      description: Manage Titles and provide custom random/summary views.
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this title.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Title'
          description: ''
      tags:
      - api
  /api/titles/{id}/summary/:
    get:
      operationId: summaryTitle
      description: Return the summary payload for a specific title.
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this title.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Title'
          description: ''
      tags:
      - api
  /api/nosolongs/{id}/:
    get:
      operationId: retrieveNoSoLong
      description: Create NoSoLong quotes and manage votes.
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this no so long.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoSoLong'
          description: ''
      tags:
      - api
    put:
      operationId: updateNoSoLong
      description: Create NoSoLong quotes and manage votes.
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this no so long.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoSoLongUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NoSoLongUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/NoSoLongUpdate'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoSoLongUpdate'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateNoSoLong
      description: Create NoSoLong quotes and manage votes.
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this no so long.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoSoLongUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NoSoLongUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/NoSoLongUpdate'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoSoLongUpdate'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyNoSoLong
      description: Create NoSoLong quotes and manage votes.
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this no so long.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/auth/token/:
    post:
      operationId: createTokenObtainPair
      description: 'Takes a set of user credentials and returns an access and refresh
        JSON web

        token pair to prove the authentication of those credentials.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
      tags:
      - api
  /api/auth/token/refresh/:
    post:
      operationId: createTokenRefresh
      description: 'Takes a refresh type JSON web token and returns an access type
        JSON web

        token if the refresh token is valid.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
      tags:
      - api
  /api/auth/register/:
    post:
      operationId: createRegister
      description: Register a new user and return JWT pair.
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/titles/:
    post:
      operationId: createTitle
      description: Manage Titles and provide custom random/summary views.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Title'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Title'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Title'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Title'
          description: ''
      tags:
      - api
  /api/nosolongs/:
    post:
      operationId: createNoSoLong
      description: Create NoSoLong quotes and manage votes.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoSoLongCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NoSoLongCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/NoSoLongCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoSoLongCreate'
          description: ''
      tags:
      - api
  /api/nosolongs/{id}/vote/:
    post:
      operationId: voteNoSoLong
      description: Create NoSoLong quotes and manage votes.
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this no so long.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoSoLong'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NoSoLong'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/NoSoLong'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoSoLong'
          description: ''
      tags:
      - api
components:
  schemas:
    Title:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        category:
          enum:
          - book
          - movie
          - tvseries
          - tvshow
          - podcast
          - speech
          - other
          type: string
        author:
          type: string
          maxLength: 255
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - name
      - category
    NoSoLong:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            name:
              type: string
              maxLength: 255
            category:
              enum:
              - book
              - movie
              - tvseries
              - tvshow
              - podcast
              - speech
              - other
              type: string
            author:
              type: string
              maxLength: 255
            created_at:
              type: string
              format: date-time
              readOnly: true
          required:
          - name
          - category
          readOnly: true
        user:
          type: object
          properties:
            email:
              type: string
              format: email
              readOnly: true
            display_name:
              type: string
              maxLength: 150
          readOnly: true
        text:
          type: string
        score:
          type: integer
          readOnly: true
        upvotes:
          type: integer
          readOnly: true
        downvotes:
          type: integer
          readOnly: true
        current_user_vote:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - text
    TokenObtainPair:
      type: object
      properties:
        email:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
    TokenRefresh:
      type: object
      properties:
        refresh:
          type: string
        access:
          type: string
          readOnly: true
      required:
      - refresh
    NoSoLongCreate:
      type: object
      properties:
        title:
          type: integer
        text:
          type: string
      required:
      - title
      - text
    NoSoLongUpdate:
      type: object
      properties:
        text:
          type: string
      required:
      - text
