services:
  db:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # Persist DB data in ./pgdata on the host for easy inspection/backups
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data/pgdata
        options: userns=keep-id
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: backend/Containerfile
    restart: unless-stopped
    env_file:
      - backend/.env.podman
    depends_on:
      db:
        condition: service_healthy
    ports:
      # host:container
      - ${HOST_PORT}:8000
    # No container volumes here; bind mount is handled under db
